apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: accelerators-list 
  namespace: accelerator-system
spec:
  serviceAccountName: accelerator-controller-manager

  fetch:
  - git:
      url: https://github.com/jmconelogin/spring-sql-jpa-cvs
      ref: features/aetnaJava
  - git:
      url: https://github.com/jmconelogin/spring-sql-jpa-cvs
      ref: origin/main
  - git:
      url: https://github.com/jmconelogin/asp-net-core-sql-accelerator
      ref: origin/main
  - git:
      url: https://github.com/jmconelogin/node-express-cvs
      ref: origin/main
  - git:
      url: https://github.com/jmconelogin/python-functions-cvs
      ref: origin/main
  template:
  - ytt: {}
  deploy: 
  - kapp: {}
